
name: Package Application with Pyinstaller

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p src/dist/windows

    - name: Package Application
      uses: JackMcKew/pyinstaller-action-windows@v0.1.2
      with:
        path: src

    - uses: actions/upload-artifact@v3.1.0    
      with:
        name: startrevit
        path: src/dist/windows
  
    - uses: actions/download-artifact@v3.0.0
      with:
        name: startrevit
        path: src/dist/windows
        
    - name: Display structure of downloaded files
      run: ls -R
      working-directory: src/dist/windows
